create database customer_behavior
select * from customer

--Q1. What is the total revenue generated by male vs. female customers?

select 
      gender  as Gender , 
      sum(purchase_Amount) as Total_Revenue 
from customer 
group by gender 

--Q2. Which customer customers used a discount but still spent more than the average purchase amount?

select customer_id ,purchase_amount 
from customer
where discount_applied = 'yes' and purchase_amount >(
select AVG(purchase_amount) from customer)


--Q3. Which are the top 5 products with the highest average review rating?

select Top 5 
        item_purchased ,
        round(avg(review_rating),2) as avg_rating
from customer 
group by item_purchased
order by avg_rating desc 


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select 
      shipping_type , 
      AVG(purchase_amount) as avg_puchased 
from customer
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


select 
     subscription_status  , 
     count(customer_id ) as Total_customer,
     AVG(purchase_amount) as avg_puchased,
     sum(purchase_amount) as Total_Revenue
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT TOP 5
       item_purchased,
      (
           SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100.0
           / COUNT(*)
           
       ) AS Discount_Percentage
FROM customer
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC;





--Q7. Segment customers into New, Returning, and Loyal based on their total number 
--of previous purchases, and show the count of each segment.

select 
     Customer_Segment,
     count(customer_id) as Total_customer 
from (
        select *,
        case when previous_purchases = 1 then 'New_customer'
        when previous_purchases <= 10 then 'Returning_Customer' 
        else 'Loyal customer' end as Customer_Segment
        from customer ) as t
group by Customer_Segment


--Q8. What are the top 3 most purchased products within each category?

select 
     category ,
     item_purchased , 
     Total_Purchased 
from (
       select 
       category , 
       item_purchased, 
       count(customer_id) as Total_Purchased ,
        Row_number() over (Partition by Category order by count(customer_id) desc) as rnk from customer
        group by  category , item_purchased ) as t
 where rnk <=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select 
       subscription_status ,
       count(customer_id) as repeat_buyer   
from customer
where previous_purchases > 5 
group by subscription_status



--Q10. What is the revenue contribution of each age group?

select 
     Age_group,
     sum(purchase_amount) * 100 / (select sum(purchase_amount) from customer) as Revenue_Contribution 
from customer
group by Age_group
order by Revenue_Contribution desc